# Generated by Django 4.1.7 on 2023-04-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employess',
            old_name='DateofJoining',
            new_name='DateOfJoining',
        ),
        migrations.RenameField(
            model_name='employess',
            old_name='DepartmentName',
            new_name='Department',
        ),
    ]
